apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-app
  template:
    metadata:
      labels:
        app: gym-app
    spec:
      containers:
      - name: gym-app
        image: gym-app
        ports:
        - containerPort: 5000
